// src/app/features/portfolio/portfolio.component.ts
import {
  Component, signal, HostListener, OnInit, OnDestroy,
  ElementRef, ViewChildren, QueryList, AfterViewInit
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { ThemeToggleComponent } from '../../shared/components/theme-toggle/theme-toggle.component';
import { ScrollProgressComponent } from '../../shared/components/scroll-progress/scroll-progress.component';
import { TypingAnimationComponent } from '../../shared/components/typing-animation/typing-animation.component';
import { ParticleBackgroundComponent } from '../../shared/components/particle-background/particle-background.component';
import { LoadingScreenComponent } from '../../shared/components/loading-screen/loading-screen.component';
import { SkillsProficiencyComponent } from './components/skills-proficiency/skills-proficiency.component';
import { TestimonialsComponent } from './components/testimonials/testimonials.component';
import { ContactFormComponent } from './components/contact-form/contact-form.component';

const PROJECTS = [
  {
    title: 'E-Commerce Platform',
    description: 'Full-stack e-commerce solution with Angular frontend, Node.js backend, and MongoDB database. Features include user authentication, payment integration, and admin dashboard.',
    tech: ['Angular', 'Node.js', 'MongoDB', 'Express.js', 'Stripe API'],
    github: '#', live: '#', image: '/placeholder.svg',
  },
  {
    title: 'Task Management System',
    description: 'Collaborative project management tool with real-time updates, file sharing, and team communication features built using MEAN stack.',
    tech: ['Angular', 'Node.js', 'MongoDB', 'Socket.io', 'JWT'],
    github: '#', live: '#', image: '/placeholder.svg',
  },
  {
    title: 'Social Media Dashboard',
    description: 'Analytics dashboard for social media management with data visualization, scheduled posting, and performance tracking.',
    tech: ['React', 'Node.js', 'MongoDB', 'Chart.js', 'Express.js'],
    github: '#', live: '#', image: '/placeholder.svg',
  },
];

const EXPERIENCE = [
  {
    title: 'Senior Full Stack Developer',
    role: 'Technology Analyst',
    company: 'at Infosys Ltd.',
    period: '2025 - Present',
    description: 'Driving end-to-end development of scalable MEAN stack applications with a focus on performance, reusability, and maintainability. Mentoring junior developers and collaborating across teams to deliver high-quality, production-ready solutions.',
  },
  {
    title: 'Full Stack Developer',
    role: 'Senior Systems Engineer',
    company: 'at Infosys Ltd.',
    period: '2023 - 2024',
    description: 'Led full-stack development efforts using Angular and Node.js, integrating APIs and ensuring responsive, accessible UI/UX across platforms. Actively contributed to Agile processes, documentation, and mentoring to support team productivity and code quality.',
  },
  {
    title: 'Angular Developer',
    role: 'Systems Engineer',
    company: 'at Infosys Ltd.',
    period: '2021 - 2023',
    description: 'Built and maintained robust web applications with a focus on frontend responsiveness and backend reliability. Ensured smooth delivery through active involvement in Agile practices, API integrations, and continuous performance optimization.',
  },
];

@Component({
  selector: 'app-portfolio',
  standalone: true,
  imports: [
    CommonModule,
    LucideAngularModule,
    ThemeToggleComponent,
    ScrollProgressComponent,
    TypingAnimationComponent,
    ParticleBackgroundComponent,
    LoadingScreenComponent,
    SkillsProficiencyComponent,
    TestimonialsComponent,
    ContactFormComponent,
  ],
  templateUrl: './portfolio.component.html',
})
export class PortfolioComponent {
  isMobileMenuOpen = signal(false);
  isScrolled = signal(false);

  projects = PROJECTS;
  experience = EXPERIENCE;
  currentYear = new Date().getFullYear();

  @HostListener('window:scroll')
  onScroll(): void {
    this.isScrolled.set(window.scrollY > 50);
  }

  toggleMenu(): void {
    this.isMobileMenuOpen.update(v => !v);
  }

  closeMenu(): void {
    this.isMobileMenuOpen.set(false);
  }

  scrollTo(id: string): void {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
    this.closeMenu();
  }

  isLast(index: number): boolean {
    return index === this.experience.length - 1;
  }
}

<app-loading-screen></app-loading-screen>

<div class="min-h-screen bg-background relative">
  <app-particle-background></app-particle-background>
  <app-scroll-progress></app-scroll-progress>

  <!-- Navigation -->
  <nav
    [class]="isScrolled()
      ? 'fixed top-1 w-full z-40 transition-all duration-300 bg-background/95 backdrop-blur-md border-b shadow-sm'
      : 'fixed top-1 w-full z-40 transition-all duration-300 bg-background/80 backdrop-blur-sm'"
  >
    <div class="container mx-auto px-4 py-4">
      <div class="flex justify-between items-center">
        <div class="text-xl font-bold transition-all duration-300 hover:scale-105">Tarun Gurugubelli</div>

        <!-- Desktop Nav -->
        <div class="hidden md:flex items-center space-x-6">
          <a (click)="scrollTo('about')" class="cursor-pointer hover:text-primary transition-all duration-300 hover:scale-105">About</a>
          <a (click)="scrollTo('skills')" class="cursor-pointer hover:text-primary transition-all duration-300 hover:scale-105">Skills</a>
          <a (click)="scrollTo('projects')" class="cursor-pointer hover:text-primary transition-all duration-300 hover:scale-105">Projects</a>
          <a (click)="scrollTo('experience')" class="cursor-pointer hover:text-primary transition-all duration-300 hover:scale-105">Experience</a>
          <a (click)="scrollTo('testimonials')" class="cursor-pointer hover:text-primary transition-all duration-300 hover:scale-105">Testimonials</a>
          <a (click)="scrollTo('contact')" class="cursor-pointer hover:text-primary transition-all duration-300 hover:scale-105">Contact</a>
          <app-theme-toggle></app-theme-toggle>
        </div>

        <!-- Mobile Nav Toggle -->
        <div class="md:hidden flex items-center gap-2">
          <app-theme-toggle></app-theme-toggle>
          <button
            (click)="toggleMenu()"
            class="inline-flex items-center justify-center h-10 w-10 rounded-md hover:bg-accent hover:text-accent-foreground transition-all duration-300 hover:scale-110"
          >
            @if (isMobileMenuOpen()) {
              <lucide-icon name="x" [size]="24"></lucide-icon>
            } @else {
              <lucide-icon name="menu" [size]="24"></lucide-icon>
            }
          </button>
        </div>
      </div>

      <!-- Mobile Menu -->
      <div
        [class]="isMobileMenuOpen()
          ? 'md:hidden transition-all duration-300 overflow-hidden max-h-64 opacity-100'
          : 'md:hidden transition-all duration-300 overflow-hidden max-h-0 opacity-0'"
      >
        <div class="py-4 space-y-2 border-t mt-4">
          <a (click)="scrollTo('about')" class="block py-2 cursor-pointer hover:text-primary transition-all duration-300 hover:translate-x-2">About</a>
          <a (click)="scrollTo('skills')" class="block py-2 cursor-pointer hover:text-primary transition-all duration-300 hover:translate-x-2">Skills</a>
          <a (click)="scrollTo('projects')" class="block py-2 cursor-pointer hover:text-primary transition-all duration-300 hover:translate-x-2">Projects</a>
          <a (click)="scrollTo('experience')" class="block py-2 cursor-pointer hover:text-primary transition-all duration-300 hover:translate-x-2">Experience</a>
          <a (click)="scrollTo('testimonials')" class="block py-2 cursor-pointer hover:text-primary transition-all duration-300 hover:translate-x-2">Testimonials</a>
          <a (click)="scrollTo('contact')" class="block py-2 cursor-pointer hover:text-primary transition-all duration-300 hover:translate-x-2">Contact</a>
        </div>
      </div>
    </div>
  </nav>

  <!-- Hero Section -->
  <section class="pt-20 pb-16 px-4 relative z-10">
    <div class="container mx-auto text-center">
      <div class="mb-8">
        <div class="animate-in zoom-in duration-700">
          <img
            src="/tarun.png"
            alt="Profile"
            width="150" height="150"
            class="rounded-full mx-auto mb-6 border-4 border-primary/20 transition-all duration-500 hover:scale-110 hover:border-primary/40 w-[150px] h-[150px] object-cover"
          />
        </div>
        <h1 class="text-4xl md:text-6xl font-bold mb-4">
          <app-typing-animation text="Tarun Gurugubelli  " [speed]="150"></app-typing-animation>
        </h1>
        <p class="text-xl md:text-2xl text-muted-foreground mb-6">Senior MEAN Stack Developer</p>
        <p class="text-lg max-w-2xl mx-auto mb-8">
          Passionate full-stack developer with 4+ years of experience building scalable web applications using
          MongoDB, Express.js, Angular, and Node.js. Specialized in creating efficient, user-friendly solutions
          for complex business problems.
        </p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <a href="/resume.pdf" target="_blank">
            <button class="inline-flex items-center justify-center gap-2 h-11 px-8 rounded-md bg-primary text-primary-foreground text-sm font-medium transition-all duration-300 hover:scale-105 hover:shadow-lg hover:bg-primary/90">
              <lucide-icon name="download" [size]="16"></lucide-icon>
              Download Resume
            </button>
          </a>
          <button
            (click)="scrollTo('contact')"
            class="inline-flex items-center justify-center h-11 px-8 rounded-md border border-input bg-background text-sm font-medium transition-all duration-300 hover:scale-105 hover:bg-accent hover:text-accent-foreground"
          >
            Get In Touch
          </button>
        </div>
        <div class="flex justify-center space-x-6 pt-6">
          <a href="https://github.com/tarun-gurugubelli" target="_blank"
             class="text-muted-foreground hover:text-primary transition-all duration-300 hover:scale-125 hover:-translate-y-1">
            <lucide-icon name="code-2" [size]="24"></lucide-icon>
          </a>
          <a href="https://linkedin.com/in/tarun-gurugubelli" target="_blank"
             class="text-muted-foreground hover:text-primary transition-all duration-300 hover:scale-125 hover:-translate-y-1">
            <lucide-icon name="briefcase-business" [size]="24"></lucide-icon>
          </a>
          <a href="mailto:tarungurugubelli@outlook.com?subject=Hello&body=I wanted to reach out..."
             class="text-muted-foreground hover:text-primary transition-all duration-300 hover:scale-125 hover:-translate-y-1">
            <lucide-icon name="mail" [size]="24"></lucide-icon>
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- About Section -->
  <section id="about" class="py-16 px-4 bg-muted/50 relative z-10">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center mb-12">About Me</h2>
      <div class="grid md:grid-cols-2 gap-12 items-center">
        <div>
          <p class="text-lg mb-6">
            I'm a dedicated MEAN stack developer with a passion for creating innovative web solutions. With over
            4+ years of professional experience, I've successfully delivered numerous projects ranging from
            e-commerce platforms to enterprise applications.
          </p>
          <p class="text-lg mb-6">
            My expertise lies in building scalable, maintainable applications using modern JavaScript
            technologies. I enjoy working in collaborative environments and am always eager to learn new
            technologies and best practices.
          </p>
          <div class="grid grid-cols-2 gap-4">
            <div class="flex items-center gap-2">
              <lucide-icon name="award" [size]="20" class="text-primary"></lucide-icon>
              <span>4+ Years Experience</span>
            </div>
            <div class="flex items-center gap-2">
              <lucide-icon name="users" [size]="20" class="text-primary"></lucide-icon>
              <span>5+ Projects Completed</span>
            </div>
            <div class="flex items-center gap-2">
              <lucide-icon name="zap" [size]="20" class="text-primary"></lucide-icon>
              <span>Performance Optimization</span>
            </div>
            <div class="flex items-center gap-2">
              <lucide-icon name="server" [size]="20" class="text-primary"></lucide-icon>
              <span>Full-Stack Development</span>
            </div>
          </div>
        </div>
        <div class="space-y-6">
          <div class="rounded-lg border bg-card text-card-foreground shadow-sm transition-all duration-300 hover:scale-105 hover:shadow-lg">
            <div class="flex flex-col space-y-1.5 p-6">
              <div class="text-2xl font-semibold leading-none tracking-tight flex items-center gap-2">
                <lucide-icon name="graduation-cap" [size]="20"></lucide-icon>
                Education
              </div>
            </div>
            <div class="p-6 pt-0">
              <p class="font-semibold">Bachelor of Electronics and Communications</p>
              <p class="text-muted-foreground">JNTU - Kakinada • 2017-2021</p>
            </div>
          </div>
          <div class="rounded-lg border bg-card text-card-foreground shadow-sm transition-all duration-300 hover:scale-105 hover:shadow-lg">
            <div class="flex flex-col space-y-1.5 p-6">
              <div class="text-2xl font-semibold leading-none tracking-tight flex items-center gap-2">
                <lucide-icon name="map-pin" [size]="20"></lucide-icon>
                Location
              </div>
            </div>
            <div class="p-6 pt-0">
              <p>Visakhapatnam, AP</p>
              <p class="text-muted-foreground">Open to opportunities</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Skills Section -->
  <section id="skills" class="py-16 px-4 relative z-10">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center mb-12">Technical Skills</h2>
      <app-skills-proficiency></app-skills-proficiency>
    </div>
  </section>

  <!-- Projects Section -->
  <section id="projects" class="py-16 px-4 bg-muted/50 relative z-10">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center mb-12">Featured Projects</h2>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        @for (project of projects; track project.title) {
          <div class="rounded-lg border bg-card text-card-foreground shadow-sm overflow-hidden transition-all duration-500 hover:scale-105 hover:shadow-xl group flex flex-col">
            <div class="aspect-video relative overflow-hidden bg-muted">
              <img
                [src]="project.image"
                [alt]="project.title"
                class="w-full h-full object-cover transition-all duration-500 group-hover:scale-110"
              />
              <div class="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300"></div>
            </div>
            <div class="flex flex-col space-y-1.5 p-6">
              <div class="text-2xl font-semibold leading-none tracking-tight group-hover:text-primary transition-colors duration-300">
                {{ project.title }}
              </div>
              <div class="text-sm text-muted-foreground">{{ project.description }}</div>
            </div>
            <div class="p-6 pt-0 flex-1 flex flex-col justify-end">
              <div class="flex flex-wrap gap-2 mb-4">
                @for (tech of project.tech; track tech) {
                  <span class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-all duration-300 hover:scale-110">
                    {{ tech }}
                  </span>
                }
              </div>
              <div class="flex gap-2">
                <a [href]="project.github" target="_blank" rel="noopener noreferrer"
                   class="inline-flex items-center justify-center gap-2 h-9 px-3 rounded-md border border-input bg-background text-sm font-medium transition-all duration-300 hover:scale-105 hover:bg-accent hover:text-accent-foreground">
                  <lucide-icon name="code-2" [size]="16"></lucide-icon>
                  Code
                </a>
                @if (project.live) {
                  <a [href]="project.live" target="_blank" rel="noopener noreferrer"
                     class="inline-flex items-center justify-center gap-2 h-9 px-3 rounded-md bg-primary text-primary-foreground text-sm font-medium transition-all duration-300 hover:scale-105 hover:bg-primary/90">
                    <lucide-icon name="external-link" [size]="16"></lucide-icon>
                    Live Demo
                  </a>
                }
              </div>
            </div>
          </div>
        }
      </div>
    </div>
  </section>

  <!-- Testimonials Section -->
  <section id="testimonials" class="py-16 px-4 relative z-10">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center mb-4">Testimonials</h2>
      <p class="text-center text-muted-foreground mb-12">What my colleagues and collaborators say</p>
      <app-testimonials (openFormRequest)="openTestimonialForm()"></app-testimonials>
    </div>
  </section>

  <!-- Experience Section -->
  <section id="experience" class="py-16 px-4 relative z-10">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center mb-12">Work Experience</h2>
      <div class="max-w-3xl mx-auto">
        @for (exp of experience; track exp.title; let i = $index) {
          <div class="relative">
            @if (!isLast(i)) {
              <div class="absolute left-6 top-12 w-0.5 h-24 bg-border"></div>
            }
            <div class="flex gap-6 mb-8">
              <div class="flex-shrink-0">
                <div class="w-12 h-12 bg-primary rounded-full flex items-center justify-center">
                  <lucide-icon name="building" [size]="24" class="text-primary-foreground"></lucide-icon>
                </div>
              </div>
              <div class="rounded-lg border bg-card text-card-foreground shadow-sm flex-1 transition-all duration-300 hover:scale-105 hover:shadow-lg">
                <div class="flex flex-col space-y-1.5 p-6">
                  <div class="text-2xl font-semibold leading-none tracking-tight">{{ exp.title }}</div>
                  <div class="text-sm text-muted-foreground flex flex-wrap items-center gap-2">
                    <span>{{ exp.role }}</span>
                    <span>{{ exp.company }}</span>
                    <span class="w-px h-4 bg-border inline-block"></span>
                    <span class="flex items-center gap-1">
                      <lucide-icon name="calendar" [size]="16"></lucide-icon>
                      {{ exp.period }}
                    </span>
                  </div>
                </div>
                <div class="p-6 pt-0">
                  <p>{{ exp.description }}</p>
                </div>
              </div>
            </div>
          </div>
        }
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section id="contact" class="py-16 px-4 bg-muted/50 relative z-10">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center mb-12">Get In Touch</h2>
      <div class="grid md:grid-cols-2 gap-12 max-w-4xl mx-auto">
        <div>
          <h3 class="text-xl font-semibold mb-6">Let's work together</h3>
          <p class="text-muted-foreground mb-8">
            I'm always interested in new opportunities and exciting projects. Whether you have a project in mind
            or just want to chat about technology, feel free to reach out!
          </p>
          <div class="space-y-4">
            <div class="flex items-center gap-3">
              <lucide-icon name="mail" [size]="20" class="text-primary"></lucide-icon>
              <span>tarungurugubelli&#64;outlook.com</span>
            </div>
            <div class="flex items-center gap-3">
              <lucide-icon name="phone" [size]="20" class="text-primary"></lucide-icon>
              <span>+91 9515431388</span>
            </div>
            <div class="flex items-center gap-3">
              <lucide-icon name="map-pin" [size]="20" class="text-primary"></lucide-icon>
              <span>Visakhapatnam, AP</span>
            </div>
          </div>
        </div>
        <app-contact-form></app-contact-form>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="py-8 px-4 border-t relative z-10">
    <div class="container mx-auto text-center">
      <p class="text-muted-foreground">© {{ currentYear }} Tarun Gurugubelli. All rights reserved.</p>
    </div>
  </footer>

  <!-- Testimonial Form Modal — rendered at root level to escape section stacking contexts -->
  @if (showTestimonialForm()) {
    <app-testimonial-form (closed)="closeTestimonialForm()"></app-testimonial-form>
  }
</div>

// portfolio.tsx
"use client"

import type React from "react"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Mail,
  Phone,
  MapPin,
  Github,
  Linkedin,
  ExternalLink,
  Download,
  Calendar,
  Building,
  GraduationCap,
  Award,
  Users,
  Zap,
  Server,
  Menu,
  X,
} from "lucide-react"
import Image from "next/image"
import Link from "next/link"
import { ThemeToggle } from "./components/theme-toggle"
import { ScrollProgress } from "./components/scroll-progress"
import { TypingAnimation } from "./components/typing-animation"
import { ParticleBackground } from "./components/particle-background"
import { LoadingScreen } from "./components/loading-screen"
import { useIntersectionObserver } from "./hooks/use-intersection-observer"
import { Testimonials } from "./components/testimonials"
import { ContactForm } from "./components/contact-form"
import { SkillsProficiency } from "./components/skills-proficiency"
// import { Floating3DElements } from "./components/floating-3d-elements"
// import { Hero3D } from "./components/hero-3d"

const skillIcons = {
  // Frontend
  Angular: "🅰️",
  React: "⚛️",
  TypeScript: "🔷",
  JavaScript: "🟨",
  HTML5: "🌐",
  CSS3: "🎨",
  Bootstrap: "🅱️",
  "Tailwind CSS": "💨",
  RxJS: "🔄",

  // Backend
  "Node.js": "🟢",
  "Express.js": "🚀",
  "RESTful APIs": "🔗",
  GraphQL: "📊",
  "Socket.io": "⚡",
  "JWT Authentication": "🔐",

  // Database
  MongoDB: "🍃",
  MySQL: "🐬",
  PostgreSQL: "🐘",
  Redis: "🔴",
  Mongoose: "🦫",

  // Tools
  Git: "📝",
  Docker: "🐳",
  AWS: "☁️",
  Heroku: "💜",
  Postman: "📮",
  "VS Code": "💻",
  Webpack: "📦",
  "npm/yarn": "📋",
}

function AnimatedSection({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const { ref, isIntersecting } = useIntersectionObserver({ threshold: 0.1 })

  return (
    <div
      ref={ref}
      className={`transition-all duration-1000 ${
        isIntersecting ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"
      } ${className}`}
    >
      {children}
    </div>
  )
}

export default function Component() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50)
    }
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  const skills = {
    frontend: ["Angular", "React", "TypeScript", "JavaScript", "HTML5", "CSS3", "Bootstrap", "Tailwind CSS", "RxJS"],
    backend: ["Node.js", "Express.js", "RESTful APIs", "GraphQL", "Socket.io", "JWT Authentication"],
    database: ["MongoDB", "MySQL", "PostgreSQL", "Redis", "Mongoose"],
    tools: ["Git", "Docker", "AWS", "Heroku", "Postman", "VS Code", "Webpack", "npm/yarn"],
  }

  const projects = [
    {
      title: "E-Commerce Platform",
      description:
        "Full-stack e-commerce solution with Angular frontend, Node.js backend, and MongoDB database. Features include user authentication, payment integration, and admin dashboard.",
      tech: ["Angular", "Node.js", "MongoDB", "Express.js", "Stripe API"],
      github: "#",
      live: "#",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      title: "Task Management System",
      description:
        "Collaborative project management tool with real-time updates, file sharing, and team communication features built using MEAN stack.",
      tech: ["Angular", "Node.js", "MongoDB", "Socket.io", "JWT"],
      github: "#",
      live: "#",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      title: "Social Media Dashboard",
      description:
        "Analytics dashboard for social media management with data visualization, scheduled posting, and performance tracking.",
      tech: ["React", "Node.js", "MongoDB", "Chart.js", "Express.js"],
      github: "#",
      live: "#",
      image: "/placeholder.svg?height=200&width=300",
    },
  ]

  const experience = [
    {
      title: "Senior Full Stack Developer",
      role: "Technology Analyst",
      company: "at Infosys Ltd.",
      period: "2025 - Present",
      description:
        "Driving end-to-end development of scalable MEAN stack applications with a focus on performance, reusability, and maintainability. Mentoring junior developers and collaborating across teams to deliver high-quality, production-ready solutions.",
    },
    {
      title: "Full Stack Developer",
      role: "Senior Systems Engineer",
      company: "at Infosys Ltd.",
      period: "2023 - 2024",
      description:
        "Led full-stack development efforts using Angular and Node.js, integrating APIs and ensuring responsive, accessible UI/UX across platforms. Actively contributed to Agile processes, documentation, and mentoring to support team productivity and code quality.",
    },
    {
      title: "Angular Developer",
      role: "Systems Engineer",
      company: "at Infosys Ltd.",
      period: "2021 - 2023",
      description:
        "Built and maintained robust web applications with a focus on frontend responsiveness and backend reliability. Ensured smooth delivery through active involvement in Agile practices, API integrations, and continuous performance optimization.",
    },
  ]

  return (
    <>
      <LoadingScreen />
      <div className="min-h-screen bg-background relative">
        <ParticleBackground />
        {/* <Floating3DElements /> */}
        <ScrollProgress />

        {/* Navigation */}
        <nav
          className={`fixed top-1 w-full z-40 transition-all duration-300 ${
            isScrolled ? "bg-background/95 backdrop-blur-md border-b shadow-sm" : "bg-background/80 backdrop-blur-sm"
          }`}
        >
          <div className="container mx-auto px-4 py-4">
            <div className="flex justify-between items-center">
              <div className="text-xl font-bold transition-all duration-300 hover:scale-105">Tarun Gurugubelli</div>

              {/* Desktop Navigation */}
              <div className="hidden md:flex items-center space-x-6">
                <Link href="#about" className="hover:text-primary transition-all duration-300 hover:scale-105">
                  About
                </Link>
                <Link href="#skills" className="hover:text-primary transition-all duration-300 hover:scale-105">
                  Skills
                </Link>
                <Link href="#projects" className="hover:text-primary transition-all duration-300 hover:scale-105">
                  Projects
                </Link>
                <Link href="#experience" className="hover:text-primary transition-all duration-300 hover:scale-105">
                  Experience
                </Link>
                <Link href="#contact" className="hover:text-primary transition-all duration-300 hover:scale-105">
                  Contact
                </Link>
                <ThemeToggle />
              </div>

              {/* Mobile Navigation */}
              <div className="md:hidden flex items-center gap-2">
                <ThemeToggle />
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                  className="transition-all duration-300 hover:scale-110"
                >
                  {isMobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
                </Button>
              </div>
            </div>

            {/* Mobile Menu */}
            <div
              className={`md:hidden transition-all duration-300 overflow-hidden ${
                isMobileMenuOpen ? "max-h-64 opacity-100" : "max-h-0 opacity-0"
              }`}
            >
              <div className="py-4 space-y-2 border-t mt-4">
                <Link
                  href="#about"
                  className="block py-2 hover:text-primary transition-all duration-300 hover:translate-x-2"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  About
                </Link>
                <Link
                  href="#skills"
                  className="block py-2 hover:text-primary transition-all duration-300 hover:translate-x-2"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  Skills
                </Link>
                <Link
                  href="#projects"
                  className="block py-2 hover:text-primary transition-all duration-300 hover:translate-x-2"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  Projects
                </Link>
                <Link
                  href="#experience"
                  className="block py-2 hover:text-primary transition-all duration-300 hover:translate-x-2"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  Experience
                </Link>
                <Link
                  href="#contact"
                  className="block py-2 hover:text-primary transition-all duration-300 hover:translate-x-2"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </nav>

        {/* Hero Section */}
        <section className="pt-20 pb-16 px-4 relative z-10">
          <div className="container mx-auto text-center">
            <AnimatedSection>
              <div className="mb-8">
                {/* <Hero3D /> */}
                <div className="animate-in zoom-in duration-700 delay-200">
                  <Image
                    src="/tarun.png?height=150&width=150"
                    alt="Profile"
                    width={150}
                    height={150}
                    className="rounded-full mx-auto mb-6 border-4 border-primary/20 transition-all duration-500 hover:scale-110 hover:border-primary/40"
                  />
                </div>
                <h1 className="text-4xl md:text-6xl font-bold mb-4">
                  <TypingAnimation text="Tarun Gurugubelli  " speed={150} />
                </h1>
                <p className="text-xl md:text-2xl text-muted-foreground mb-6 animate-in slide-in-from-bottom duration-700 delay-1000">
                  Senior MEAN Stack Developer
                </p>
                <p className="text-lg max-w-2xl mx-auto mb-8 animate-in slide-in-from-bottom duration-700 delay-1200">
                  Passionate full-stack developer with 4+ years of experience building scalable web applications using
                  MongoDB, Express.js, Angular, and Node.js. Specialized in creating efficient, user-friendly solutions
                  for complex business problems.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center animate-in slide-in-from-bottom duration-700 delay-1400">  
                  <a href="/resume.pdf" target="_blank" >
                    <Button size="lg" className="gap-2 transition-all duration-300 hover:scale-105 hover:shadow-lg">
                      <Download className="w-4 h-4" />
                      Download Resume
                    </Button>
                  </a>
                  <Button variant="outline" size="lg" asChild className="transition-all duration-300 hover:scale-105">
                    <Link href="#contact">Get In Touch</Link>
                  </Button>
                </div>
                <div className="flex justify-center space-x-6 pt-6 animate-in slide-in-from-bottom duration-700 delay-1600">
                  <Link
                    href="https://github.com/tarun-gurugubelli" target="_blank"
                    className="text-muted-foreground hover:text-primary transition-all duration-300 hover:scale-125 hover:-translate-y-1"
                  >
                    <Github className="w-6 h-6" />
                  </Link>
                  <Link
                    href="https://linkedin.com/in/tarun-gurugubelli" target="_blank"
                    className="text-muted-foreground hover:text-primary transition-all duration-300 hover:scale-125 hover:-translate-y-1"
                  >
                    <Linkedin className="w-6 h-6" />
                  </Link>
                  <Link
                    href="mailto:tarungurugubelli@outlook.com?subject=Hello&body=I wanted to reach out..." target="_blank"
                    className="text-muted-foreground hover:text-primary transition-all duration-300 hover:scale-125 hover:-translate-y-1"
                  >
                    <Mail className="w-6 h-6" />
                  </Link>
                </div>
              </div>
            </AnimatedSection>
          </div>
        </section>

        {/* About Section */}
        <section id="about" className="py-16 px-4 bg-muted/50 relative z-10">
          <div className="container mx-auto">
            <AnimatedSection>
              <h2 className="text-3xl font-bold text-center mb-12">About Me</h2>
              <div className="grid md:grid-cols-2 gap-12 items-center">
                <div>
                  <p className="text-lg mb-6">
                    I'm a dedicated MEAN stack developer with a passion for creating innovative web solutions. With over
                    4+ years of professional experience, I've successfully delivered numerous projects ranging from
                    e-commerce platforms to enterprise applications.
                  </p>
                  <p className="text-lg mb-6">
                    My expertise lies in building scalable, maintainable applications using modern JavaScript
                    technologies. I enjoy working in collaborative environments and am always eager to learn new
                    technologies and best practices.
                  </p>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="flex items-center gap-2">
                      <Award className="w-5 h-5 text-primary" />
                      <span>4+ Years Experience</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Users className="w-5 h-5 text-primary" />
                      <span>5+ Projects Completed</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Zap className="w-5 h-5 text-primary" />
                      <span>Performance Optimization</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Server className="w-5 h-5 text-primary" />
                      <span>Full-Stack Development</span>
                    </div>
                  </div>
                </div>
                <div className="space-y-6">
                  <Card className="transition-all duration-300 hover:scale-105 hover:shadow-lg">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <GraduationCap className="w-5 h-5" />
                        Education
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="font-semibold">Bachelor of Electronics and Communications</p>
                      <p className="text-muted-foreground">JNTU - Kakinada • 2017-2021</p>
                    </CardContent>
                  </Card>
                  <Card className="transition-all duration-300 hover:scale-105 hover:shadow-lg">
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <MapPin className="w-5 h-5" />
                        Location
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p>Visakhapatnam, AP</p>
                      <p className="text-muted-foreground">Open to opportunities</p>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </AnimatedSection>
          </div>
        </section>

        {/* Skills Section */}
        <section id="skills" className="py-16 px-4 relative z-10">
          <div className="container mx-auto">
            <AnimatedSection>
              <h2 className="text-3xl font-bold text-center mb-12">Technical Skills</h2>
              <SkillsProficiency />
            </AnimatedSection>
          </div>
        </section>

        {/* Projects Section */}
        <section id="projects" className="py-16 px-4 bg-muted/50 relative z-10">
          <div className="container mx-auto">
            <AnimatedSection>
              <h2 className="text-3xl font-bold text-center mb-12">Featured Projects</h2>
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                {projects.map((project, index) => (
                  <AnimatedSection key={index}>
                    <Card className="overflow-hidden transition-all duration-500 hover:scale-105 hover:shadow-xl group h-full">
                      <div className="aspect-video relative overflow-hidden">
                        <Image
                          src={project.image || "/placeholder.svg"}
                          alt={project.title}
                          fill
                          className="object-cover transition-all duration-500 group-hover:scale-110"
                        />
                        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300" />
                      </div>
                      <CardHeader>
                        <CardTitle className="group-hover:text-primary transition-colors duration-300">
                          {project.title}
                        </CardTitle>
                        <CardDescription>{project.description}</CardDescription>
                      </CardHeader>
                      <CardContent>
                        <div className="flex flex-wrap gap-2 mb-4">
                          {project.tech.map((tech) => (
                            <Badge
                              key={tech}
                              variant="outline"
                              className="text-xs transition-all duration-300 hover:scale-110"
                            >
                              {tech}
                            </Badge>
                          ))}
                        </div>
                        <div className="flex gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            asChild
                            className="transition-all duration-300 hover:scale-105"
                          >
                            <Link href={project.github} className="gap-2">
                              <Github className="w-4 h-4" />
                              Code
                            </Link>
                          </Button>
                          <Button size="sm" asChild className="transition-all duration-300 hover:scale-105">
                            <Link href={project.live} className="gap-2">
                              <ExternalLink className="w-4 h-4" />
                              Live Demo
                            </Link>
                          </Button>
                        </div>
                      </CardContent>
                    </Card>
                  </AnimatedSection>
                ))}
              </div>
            </AnimatedSection>
          </div>
        </section>

        {/* Testimonials Section */}
        <section className="py-16 px-4 relative z-10">
          <div className="container mx-auto">
            <AnimatedSection>
              <h2 className="text-3xl font-bold text-center mb-12">What Team Say</h2>
              <Testimonials />
            </AnimatedSection>
          </div>
        </section>

        {/* Experience Section */}
        <section id="experience" className="py-16 px-4 relative z-10">
          <div className="container mx-auto">
            <AnimatedSection>
              <h2 className="text-3xl font-bold text-center mb-12">Work Experience</h2>
              <div className="max-w-3xl mx-auto">
                {experience.map((exp, index) => (
                  <AnimatedSection key={index}>
                    <div className="relative">
                      {index !== experience.length - 1 && (
                        <div className="absolute left-6 top-12 w-0.5 h-24 bg-border"></div>
                      )}
                      <div className="flex gap-6 mb-8">
                        <div className="flex-shrink-0">
                          <div className="w-12 h-12 bg-primary rounded-full flex items-center justify-center">
                            <Building className="w-6 h-6 text-primary-foreground" />
                          </div>
                        </div>
                        <Card className="flex-1 transition-all duration-300 hover:scale-105 hover:shadow-lg">
                          <CardHeader>
                            <CardTitle>{exp.title}</CardTitle>
                            <CardDescription className="flex items-center gap-2">
                              <span>{exp.role}</span>
                              <span>{exp.company}</span>
                              <Separator orientation="vertical" className="h-4" />
                              <span className="flex items-center gap-1">
                                <Calendar className="w-4 h-4" />
                                {exp.period}
                              </span>
                            </CardDescription>
                          </CardHeader>
                          <CardContent>
                            <p>{exp.description}</p>
                          </CardContent>
                        </Card>
                      </div>
                    </div>
                  </AnimatedSection>
                ))}
              </div>
            </AnimatedSection>
          </div>
        </section>

        {/* Contact Section */}
        <section id="contact" className="py-16 px-4 bg-muted/50 relative z-10">
          <div className="container mx-auto">
            <AnimatedSection>
              <h2 className="text-3xl font-bold text-center mb-12">Get In Touch</h2>
              <div className="grid md:grid-cols-2 gap-12 max-w-4xl mx-auto">
                <div>
                  <h3 className="text-xl font-semibold mb-6">Let's work together</h3>
                  <p className="text-muted-foreground mb-8">
                    I'm always interested in new opportunities and exciting projects. Whether you have a project in mind
                    or just want to chat about technology, feel free to reach out!
                  </p>
                  <div className="space-y-4">
                    <div className="flex items-center gap-3">
                      <Mail className="w-5 h-5 text-primary" />
                      <span>tarungurugubelli@outlook.com</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <Phone className="w-5 h-5 text-primary" />
                      <span>+91 9515431388</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <MapPin className="w-5 h-5 text-primary" />
                      <span>Visakhapatnam, AP</span>
                    </div>
                  </div>
                </div>
                <ContactForm />
              </div>
            </AnimatedSection>
          </div>
        </section>

        {/* Footer */}
        <footer className="py-8 px-4 border-t relative z-10">
          <div className="container mx-auto text-center">
            <p className="text-muted-foreground">© {new Date().getFullYear()} Tarun Gurugubelli. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </>
  )
}
